### PR TITLE
Remove print and fix return value.

### PR DESCRIPTION
**Pull request by ibz**

### CODE REVIEW

**Comment by kornpow** [comment]
Thanks for the PR, let me check this out soon and hopefully get it merged in soon

**Comment by kornpow** [comment]
Merged it and deployed to Pypi: [0.3.37](https://pypi.org/project/lnd-grpc-client/0.3.37/)

**Comment by kornpow** [comment]
Thanks for the PR, glad to have some help!

**Comment by ibz** [comment]
Thank **you** for continuing to maintain this library! We all need this!

**Pull request merged**
