### PR TITLE
Added Keysend support to LNDClient.send_payment

### PR DESCRIPTION
**Pull request by valcanobacon**
I started integrating this library into https://github.com/valcanobacon/BoostIRC and I need support for keysend. I changed LNDClient.send_payment to keysend if payment_request is None. I am not sure if this is the best way to organize it, let me know what you think and I can add, remove or just reorganize. Thanks!

## Test Script

```python
import json
import codecs
from lndgrpc import LNDClient


address="localhost"
port=10009
macaroon="./admin.macaroon"
tlscert="./tls.cert"
pubkey = "REDACTED"


lnd = LNDClient(
    f"{address}:{port}",
    macaroon_filepath=macaroon,
    cert_filepath=tlscert,
)

custom_records = [
    (7629169, json.dumps({"app_name": "test"}).encode("utf8")), # podcasting 2.0 TLV to make sure the keysend TLV is added correctly
]

dest = codecs.decode(pubkey, "hex")

response = lnd.send_payment(payment_request=None, fee_limit_msat=10*1000, dest=dest, amt_msat=10*100, dest_custom_records=custom_records)

print(response)
```

### CODE REVIEW

**Comment by valcanobacon** [comment]
I realized I can do this without any code changes.  

```python
import json
import codecs
from lndgrpc import LNDClient

import hashlib
import secrets


address="localhost"
port=10009
macaroon="./admin.macaroon"
tlscert="./tls.cert"
pubkey = "REDACTED"


lnd = LNDClient(
    f"{address}:{port}",
    macaroon_filepath=macaroon,
    cert_filepath=tlscert,
)

secret = secrets.token_bytes(32)
hashed_secret = hashlib.sha256(secret).hexdigest()
dest_custom_records = [
    (5482373484, secret),
    (7629169, json.dumps({"app_name": "test"}).encode("utf8")), # podcasting 2.0 TLV to make sure the keysend TLV is added correctly
]
response = lnd.send_payment(
    payment_request=None,
    payment_hash=bytes.fromhex(hashed_secret),
    fee_limit=10 * 1000, 
    dest=codecs.decode(pubkey, "hex"),
)

print(response)
```

**Comment by kornpow** [comment]
yeah I thought that was the case. Here is my keysend example script: https://github.com/kornpow/lnd-grpc-client/blob/master/examples/send-keysend.py

Maybe you can help me cleanup the example script?

**Comment by kornpow** [comment]
In general, I want to keep `client.py` fairly barebones to the underlying API. In some places here and there I allow passing in hex instead of bytes. A higher level api could be good, to simplify usage of keysend, and other things

**Comment by valcanobacon** [comment]
I like your example but maybe the mvp like the one I have above is useful.

**Comment by kornpow** [comment]
Yeah I think so. I also saw a few different custom record codes which supposedly worked for keysend. 

I was trying to keysend to my Breez wallet, which is why I had all the hop hints there. I don’t think I was able to get it working to Breez. 

Feel free to add a commit to that file though. Delete anything you’d like and include what you think is important.

**Pull request closed without merging**
