### PR TITLE
Add add_index and settle_index parameters.

### PR DESCRIPTION
**Pull request by ibz**

### CODE REVIEW

**Comment by ibz** [comment]
Hey, @kornpow ! Could you approve this please?

**Comment by kornpow** [comment]
merged!

**Comment by ibz** [comment]
Thank you! Could you also bump the version and release, @kornpow?

**Comment by kornpow** [comment]
Yep!
https://pypi.org/project/lnd-grpc-client/0.3.40/

**Comment by ibz** [comment]
Hey @kornpow - I installed 0.3.40 and my change doesn't seem to be there.

**Comment by kornpow** [comment]
@ibz sorry
https://pypi.org/project/lnd-grpc-client/0.3.41/

**Pull request merged**
